# Generated by Django 4.0.4 on 2022-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
