# Generated by Django 4.0.4 on 2022-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_boy',
            field=models.BooleanField(default=False),
        ),
    ]
