# Generated by Django 4.0.4 on 2022-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refered_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
