# Generated by Django 4.0.4 on 2022-05-02 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminn', '0007_remove_order_user_delete_midorder_delete_order'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(max_length=20)),
                ('rz_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rz_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('service_cost', models.FloatField(default=0)),
                ('service_description', models.TextField()),
                ('service_date', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.order')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminn.service')),
            ],
        ),
    ]
