# Generated by Django 4.0.4 on 2022-05-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='service_id',
            new_name='sid',
        ),
    ]
