# Generated by Django 4.0.4 on 2022-05-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_service_id_midorder_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='services',
            new_name='service',
        ),
    ]
