# Generated by Django 4.0.4 on 2022-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_services_midorder_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midorder',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='midorder',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
