# Generated by Django 4.0.4 on 2022-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_midorder_end_time_alter_midorder_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
