# Generated by Django 4.0.4 on 2022-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='midorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
    ]
