# Generated by Django 4.0.2 on 2022-05-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_midorder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='midorder',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midorder',
            name='status',
            field=models.CharField(default='order_placed', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
