# Generated by Django 4.0.4 on 2022-05-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_midorder_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midorder',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='order_placed', max_length=100),
        ),
    ]
