# Generated by Django 4.0.4 on 2022-05-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0011_remove_midorder_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midorder',
            name='delivery_boy',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provided_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
