# Generated by Django 4.0.4 on 2022-05-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0010_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_remove_midorder_delivery_boy_order_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminn.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
