# Generated by Django 4.0.4 on 2022-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_balance_use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
