# Generated by Django 4.0.4 on 2022-06-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_order_wallet_balance_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midorder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='midorder',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='midorder',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='midorder',
            name='sid',
        ),
    ]
