# Generated by Django 4.0.4 on 2022-04-28 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('coupon_id', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField()),
                ('discount', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_price', models.FloatField(default=0)),
                ('actual_price', models.FloatField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('min_time_range', models.IntegerField(default=1)),
                ('max_time_range', models.IntegerField(default=2)),
                ('min_strength', models.IntegerField(default=1)),
                ('max_strength', models.IntegerField(default=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.category')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('services', models.ManyToManyField(to='adminn.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sub_category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.category')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.subcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(max_length=20)),
                ('rz_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rz_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('service_cost', models.FloatField(default=0)),
                ('service_description', models.TextField()),
                ('service_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.order')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('other', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.service')),
            ],
        ),
    ]
