# Generated by Django 4.0.4 on 2022-05-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0005_alter_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midorder',
            name='time',
        ),
        migrations.AddField(
            model_name='midorder',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midorder',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='adminn.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midorder',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
