# Generated by Django 4.0.4 on 2022-05-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0006_remove_midorder_time_midorder_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='MidOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
