# Generated by Django 4.0.4 on 2022-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0007_remove_order_user_delete_midorder_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='top', max_length=255),
        ),
    ]
