# Generated by Django 4.0.4 on 2022-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0010_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.CharField(max_length=100)),
                ('is_percentage', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
