# Generated by Django 4.0.4 on 2022-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0012_category_is_deleted_service_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
